apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-payroll-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-payroll
  template:
    metadata:
      labels:
        app: employee-payroll
    spec:
      containers:
      - name: employee-payroll-container
        image: phx.ocir.io/oracleamerica/employee-payroll:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ocirsecret